libc_a_SOURCES += \
    %D%/applet_main.c \
    %D%/applet_reset.c \
    %D%/applet_startup.c \
    %D%/crt0.c \
    %D%/exit.c \
    %D%/io.c \
    %D%/malloc.c \
    %D%/mutekishims_utils.c \
    %D%/nowide.c \
    %D%/sleep.c \
    %D%/syscalls.c
