libc_a_SOURCES += \
    %D%/applet_main.c \
    %D%/applet_reset.c \
    %D%/applet_startup.c \
    %D%/closedir.c \
    %D%/crt0.c \
    %D%/cwd.c \
    %D%/dirfd.c \
    %D%/exit.c \
    %D%/io.c \
    %D%/malloc.c \
    %D%/mkdir.c \
    %D%/mutekishims_utils.c \
    %D%/nowide.c \
    %D%/opendir.c \
    %D%/readdir.c \
    %D%/readdir_r.c \
    %D%/rewinddir.c \
    %D%/scandir.c \
    %D%/seekdir.c \
    %D%/sleep.c \
    %D%/syscalls.c \
    %D%/telldir.c
